// export { default as AddPostPage } from "./AddPostPage";
// export { default as ForgotPassword } from "./ForgotPassword";
// export { default as Friend } from "./Friend";
// export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Chat } from "./Chat";
// export { default as MyProfile } from "./MyProfile";
// export { default as Notification } from "./Notification";
// export { default as UserPersonalInformation } from "./UserPersonalInformation";
// export { default as Register } from "./Register";
// export { default as AddPost } from "./AddPostPage";
